### ISSUE TITLE
Refactoring: Creación de User Service

### ISSUE THREAD

**Issue by jonatanvicente** [IT-Academy-BCN/ita-challenges-frontend#300]
Es necesario crear un Servicio denominado user.service.ts que gestione el estado del usuario en cada momento:
* Es complementario a Auth Service: User Service almacenará variables de estado siguientes:
    - Variable que indique si está registrado o no (de momento no necesitaremos usar esta variable).
    - Variable que indique si está logged o no

![Image](https://github.com/IT-Academy-BCN/ita-challenges-frontend/assets/1706861/70f61d81-98fa-4685-bdcc-a91b3c2f828c)

**Comment by adptCode** [comment]
Actualizado el código con la rama `develop` y añadido la lógica para gestionar la flag `solutionSent` en el `UserService`.
