### ISSUE TITLE
Challenge Screen List

### ISSUE THREAD

**Issue by jonatanvicente** [IT-Academy-BCN/ita-challenges-frontend#366]
* Revisión diseño / funcionalidad
**Implemented by Eloi**

**Comment by codenaud** [comment]
Revisión de la pantalla challenge y su funcionalidad.
Funcionalidad => Correcto! Funciona todo.
Diseño => Aquí hay varios puntos de revisión con el tema scroll. 
1 - Eliminamos la paginación en responsive y hacemos un scroll infinito? **OK**
Ejemplo: https://ita-profiles.netlify.app/
2 - Reducimos espacios arriba y abajo (margin/padding) para ganar pantalla. **OK**
3 - Se tiene que ver la versión de release? **NO**
4 - En el FIGMA no aparece el NAV. Hay que ocultarlo? **SI**
5 - Botón HAMBURGUESA: No definido en Figma ita-challenge, véase ita-wiki. Construcción de uno similar.

**Comment by jonatanvicente** [comment]
Comentarios de @Yul1b3th 


## Revisión de diseño / funcionalidad (Versión móvil)

**_En cuanto a diseño:_**
1. Tal vez se deba ocultar el menú de idiomas, configuración y perfil que está en el header.
2. Las etiquetas h2 actualmente tienen un font-size de 26px, pero en Figma tienen un font-size de 23px. Para los font-size, es recomendable usar las medidas en rem.
3. El nuevo header, que tiene un fondo negro, parece tener poca altura. Actualmente, el botón en el header tiene 20px de alto, pero se recomienda que los botones tengan una altura mínima de 44px para mejorar la accesibilidad. Si el botón tiene 44px de alto, el header debería tener como mínimo 60px de altura. Sin embargo, el header actualmente tiene solo 32px de altura.
