### ISSUE TITLE
Challenge Detail Screen

### ISSUE THREAD

**Issue by jonatanvicente** [IT-Academy-BCN/ita-challenges-frontend#367]
* Revisión diseño / funcionalidad, pestañas Detalles, Soluciones, Recursos y Relacionado

**Implemented by Silvia**
**Revised by Jonatan**

**WARNING**
**Branch feature#367**
**Please, execute**
```
npx ng build --configuration production 
```
**before to make a new PR**

**Comment by Yul1b3th** [comment]
## Revisión de diseño / funcionalidad (Versión móvil)

### Botones de pestañas:

- Los botones Detalles, Soluciones y Recursos funcionan correctamente, pero en el diseño de Figma se ha omitido ‘Relacionado’.
- Sugiero la implementación de un menú desplegable ("Dropdown") para Detalles, Soluciones, Recursos y Relacionado.
- **Implementación: Aceptado dropdown por mayoría simple**

### Sección Soluciones:

- Sugiero fijar el botón '**_Enviar solución_**' en la parte inferior de la pantalla. En Figma, el botón tiene una altura de 63px.
- **OK**

### Revisión de encabezados:

- Tal vez se deban ajustar los encabezados, ya que no veo que se utilicen etiquetas h1 ni h2. **OK**
- Los títulos tienen un font-size de 26px, pero en Figma tienen un font-size de 23px. **OK**
- Los subtítulos de las secciones en Figma tienen un font-size de 16px. **OK**
- Para los tamaños de fuente, es recomendable usar medidas en rem. **OK**

### Ocultar contenido:

- En Figma no se muestra el contenido ‘**_Recursos encontrados en ITA-Wiki_**’. Tal vez se deba ocultar en la versión móvil.  **OK**

### Problemas de desplazamiento:

- No se puede hacer scroll hacia abajo para visualizar el contenido de cada pestaña: Detalles, Soluciones, Recursos.  **OK**
