### ISSUE TITLE
Capturar solucion de usuario

### ISSUE THREAD

**Issue by fran-cesc** [IT-Academy-BCN/ita-challenges-frontend#386]
**Al no estar implementado el endpoint en backend, ponemos console.log con la solución capturada**

TODO: es necesario diseñar una pipe para escapar caracteres clave del standard JSON (otra issue).
**made by Frncesc**
**reviewed by eloi**

**Comment by xapolin1979** [comment]
Todo correcto. Se ha creado en la carpeta pipes la tubería escape-java-chars.pipe.ts para escapar los caracteres raros. Pero cuando en solution.component la función onSubmitSolution() captura la solución, se debería implementar escape-java-chars.pipe.ts. He mirado ahora la rama develop para ver si estaba puesta la pipe, pero tampoco veo que esté implementada.
