### ISSUE TITLE
Revision of icons difficulty-off/on.svg & Challenge Owner

### ISSUE THREAD

**Issue by jonatanvicente** [IT-Academy-BCN/ita-challenges-frontend#392]
We need review both icons difficulty-off/on.svg and Challenge Owner on responsive.
**created by evarkiteca **
**reviewed by eloi**
![Image](https://github.com/IT-Academy-BCN/ita-challenges-frontend/assets/1706861/6d1bbbd8-1af2-42a1-be91-31bb20fe675f)

**Comment by xapolin1979** [comment]
Está todo correcto; los iconos de dificultad se encienden o se apagan según su dificultad y también pasa los tests correctamente.

**Comment by xapolin1979** [comment]
Está todo correcto; los iconos son responsivos y también pasan todos los tests.
