### ISSUE TITLE
Refactoring: huge mocks must be externalized from tests

### ISSUE THREAD

**Issue by jonatanvicente** [IT-Academy-BCN/ita-challenges-frontend#405]
Some test files contains huge mocks as, for example:
* starter.service.spect.ts
* related.service.spec.ts
* resources.service.spec.ts.
This bad practice must be removed: mocks must be loaded from folder 'Mocks' if test files needs to them.

**Implemented by Aless**
**reviewed by Eloi**

**Comment by xapolin1979** [comment]
Para mí, todo es correcto. Ha cogido las constantes que había en los tests (spec) y las ha colocado en una carpeta llamada "mocks", donde las ha clasificado en diferentes carpetas y en diferentes archivos JSON para luego importarlas en los tests. Todos los tests han pasado correctamente.
