### ISSUE TITLE
Bug: Tooltip is not translated

### ISSUE THREAD

**Issue by jonatanvicente** [IT-Academy-BCN/ita-challenges-frontend#408]
When the user changes language app, tooltips don't change their language (as is desired).

**Implemented by Aless**

**reviewed by eloi**

**Comment by xapolin1979** [comment]
Lo veo correcto, ha creado un objeto llamado tooltips donde lo ha colocado en los 3 JSON de los idiomas que estan en la carpeta i18h y lo ha llamado en challenge-card, para que salgan las traducciones tambien a pasado los test
