### ISSUE TITLE
User solutions sending mechanism

### ISSUE THREAD

**Issue by jonatanvicente** [IT-Academy-BCN/ita-challenges-frontend#472]
We need to implement a mechanism to know at the moment which challenges contain a solution sended by user.

**TASKS TO IMPLEMENT**

* When user executes log In, then we need to know which challenges user sent his solution. For that, we will request to endpoint **/itachallenge/api/v1/user/{idUser}/challenges/solutions** (by now may be use a dummy, that endpoint is not yet in production).
* The result will be saved in a variable into a User Service
* User service must be contains a method to know if user sent a solution for a determinate challenge (that returns boolean). This method should be requested by all components needs it.

**BUG TO FIX**

* Ussually, when user is logged in may see all solutions from all challenges. This working is wrong, because may be a user sent a solution to a concrete challenge, but not to all (and not should see all the solutions). It's necessary to fix that.

**Comment by adptCode** [comment]
In the dummy data, the first three challenges are set as having a solution submitted by the user. For these challenges, the button behavior accurately reflects the 'solution sent' status. For all other challenges, the buttons follow a reactive behavior and correctly update based on the solution submission status.
